version: '3.5'

services:

  service:
    container_name: compose-test-service
    image: ${DOCKER_REGISTRY-}compose-test-service
    build:
      context: ./service-src
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - dependent-service
     - redis
    environment:
     - REDIS_ADDRESS=redis
     - DEPENDENT_ENDPOINT=http://dependent-service:5010/abc
     - EXTERNAL_ENDPOINT=http://host.docker.internal/test/ok.txt
     - GOOGLE_ENDPOINT=https://www.gstatic.com/teapot/teapot.min.js
    networks:
     - compose-test
  
  dependent-service:
    container_name: compose-test-dependent-service
    image: ${DOCKER_REGISTRY-}compose-test-dependent-service
    build:
      context: ./dependent-service-src
      dockerfile: Dockerfile
    networks:
     - compose-test
  
  redis:
    image: redis
    networks:
     - compose-test

networks:
  compose-test:
    name: compose-test
    driver: bridge